### ISSUE TITLE
ofxImage + ofImage — Look into double loading protections

### ISSUE THREAD

**Issue by ericgunther** [sosolimited/ofxSoso#33]
For IBM, we integrated code into ofImage/ofxImageObject that skipped loading an image if it had already been loaded—and then assigned the correct GL texture—to conserve texture memory.

Let's get this code back in there.

**Comment by aolivier** [comment]
Should have a flag if you want to reload even if it's already there.

Static vector of everything that's loaded in ofxImageObject.  Needs filename, texture id number.

If you find one that's already loaded, you just set the ofimage's texture id to the stored id.
