### ISSUE TITLE
ofxLetterTextObject::setString calls itself

### ISSUE THREAD

**Issue by jasonlevine** [sosolimited/ofxSoso#74]
Hi Soso,

When I try to set the string of an ofxLetterTextObject like this:
`letterText->setString("test text");`

My stack explodes with calls to `ofxLetterTextObject::setString` and ends with an `EXC_BAD_ACCESS` error.  When I examined the code it seemed as if this function calls itself:

`void ofxLetterTextObject::setString(string iString) //JM 080513
{
    setString(iString);
}`

**Comment by jasonlevine** [comment]
I tried commenting out `ofxLetterTextObject::setString(string iString)` so that `ofxTextObject::setString(string iString)` would be called.  This succeeded in changing the value of the `rawText` string but did not update my letters, so I created this simple function:

`void ofxLetterTextObject::setLetters(string iString)
{
    setString(iString);
        rebuildLetters();
}`

**Comment by aolivier** [comment]
@jasonlevine Thanks for bringing this to our attention!  Fix pushed up.
