### ISSUE TITLE
ofxObject :: doMessage4f doesn't work with OF_SETCOLOR

### ISSUE THREAD

**Issue by jrolimited** [sosolimited/ofxSoso#8]
To tween color and alpha together, you need two messages: one 3f for color and one 1f for alpha.

Furthermore, setColor with 3 variables will automatically set the alpha of the object to 255.0 - we could add a separate method with 3 vars that uses the current alpha and have the 4 var method take no default

**Comment by aolivier** [comment]
add of_setcolor4, which lets you tween color and alpha together
